# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ticketbootking'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ticketbootking'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
# directories to be removed by `dbt clean`
- "target"
- "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  ticketbootking:
    # Staging models - materialized as views for fast development
    staging:
      +materialized: view
      +schema: staging

    # Core mart models - materialized as tables for performance
    marts:
      core:
        +materialized: table
        +schema: marts_core
      reporting:
        +materialized: table
        +schema: marts_reporting

    # Semantic models and metrics
    semantic_models:
      +materialized: view
      +schema: semantic_models

    metrics:
      +materialized: view
      +schema: metrics

    # Example models - keep as views
    example:
      +materialized: view
