version: 2

sources:
- name: public
  schema: public
  tables:
  - name: netflix_titles
    description: "Netflix titles dataset with movies and TV shows"

models:
- name: stg_netflix_titles
  description: "Staging model for Netflix titles data with cleaned and parsed fields"
  columns:
  - name: show_id
    description: "Unique identifier for the show"
  - name: type
    description: "Type of content - Movie or TV Show"
  - name: title
    description: "Title of the show or movie"
  - name: director
    description: "Director(s) of the content"
  - name: casts
    description: "Cast members of the content"
  - name: country
    description: "Country or countries where the content was produced"
  - name: date_added
    description: "Date when content was added to Netflix"
  - name: release_year
    description: "Year the content was released"
  - name: rating
    description: "Content rating"
  - name: duration
    description: "Original duration field from source"
  - name: genres
    description: "Genres or categories the content belongs to"
  - name: description
    description: "Description of the content"
  - name: movie_duration_minutes
    description: "Duration in minutes for movies"
  - name: tv_show_seasons
    description: "Number of seasons for TV shows"
  - name: date_added_parsed
    description: "Parsed date when content was added to Netflix"
