version: 2

sources:
- name: public
  schema: public
  tables:
  - name: netflix_titles
    description: "Netflix titles dataset with movies and TV shows"

models:
- name: stg_netflix_titles
  description: "Staging model for Netflix titles data with cleaned and parsed fields"
  columns:
  - name: show_id
    description: "Unique identifier for the show"
  - name: type
    description: "Type of content - Movie or TV Show"
  - name: title
    description: "Title of the show or movie"
  - name: release_year
    description: "Year the content was released"
  - name: rating
    description: "Content rating"
  - name: movie_duration_minutes
    description: "Duration in minutes for movies"
  - name: tv_show_seasons
    description: "Number of seasons for TV shows"
